name: Deploy React App by Branch

on:
  push:
    branches: ['**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Get sanitized branch name
        id: branch_name
        run: |
          BRANCH=${GITHUB_REF##*/}
          SANITIZED=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]/-/g' -e 's/-\{2,\}/-/g')
          echo "name=$SANITIZED" >> $GITHUB_OUTPUT

      - name: Build app
        run: npm run build

      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WEKODE_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.WEKODE_SSH_HOST }}
          REMOTE_PORT: ${{ secrets.WEKODE_SSH_PORT }}
          REMOTE_USER: ${{ secrets.WEKODE_SSH_USERNAME }}
          SOURCE: 'dist/'
          TARGET: '${{ secrets.WEKODE_ALL_SSH_PROJECT_DIRECTORY}}/frontend-${{ steps.branch_name.outputs.name }}'
          ARGS: '-avz --delete'
          CLEAN: true
