name: Deploy React App by Branch

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Get sanitized branch name
        id: get_branch
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed -e 's/[^[:alnum:]_-]/-/g')
          echo "branch=$SANITIZED_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Build app
        run: npm run build

      - name: Modify files for branch deployment
        run: |
          BRANCH_NAME=${{ steps.get_branch.outputs.branch }}
          
          # 1. Fix asset paths
          sed -i "s|='/|='/$BRANCH_NAME/|g" dist/index.html
          sed -i "s|=\"/|=\"/$BRANCH_NAME/|g" dist/index.html
          
          # 2. Fix router configuration
          find dist -type f -name '*.js' -exec sed -i \
            -e "s|history.createBrowserHistory()|history.createBrowserHistory({basename:'/$BRANCH_NAME'})|g" \
            -e "s|new Router(|new Router({basename:'/$BRANCH_NAME',|g" \
            -e "s|createBrowserRouter(|createBrowserRouter([],{basename:'/$BRANCH_NAME'})|g" {} \;
          
          # 3. Create .htaccess for routing
          cat > dist/.htaccess <<EOL
          RewriteEngine On
          RewriteBase /$BRANCH_NAME/
          
          # Redirect root to index.html
          RewriteRule ^index\.html$ - [L]
          
          # Handle client-side routing
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /$BRANCH_NAME/index.html [L]
          EOL

      - name: Deploy dist folder to server via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WEKODE_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.WEKODE_SSH_HOST }}
          REMOTE_PORT: ${{ secrets.WEKODE_SSH_PORT }}
          REMOTE_USER: ${{ secrets.WEKODE_SSH_USERNAME }}
          SOURCE: dist/
          TARGET: ${{ secrets.WEKODE_ALL_SSH_PROJECT_DIRECTORY }}/${{ steps.get_branch.outputs.branch }}
          CLEAN: true
