name: Deploy React App by Branch

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Get sanitized branch name
        id: get_branch
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed -e 's/[^[:alnum:]_-]/-/g')
          echo "branch=$SANITIZED_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Build app
        run: npm run build

      - name: Create branch-specific .htaccess
        run: |
          BRANCH_NAME=${{ steps.get_branch.outputs.branch }}
          cat > dist/.htaccess <<EOL
          RewriteEngine On
          RewriteBase /$BRANCH_NAME/

          # Redirect asset requests to correct path
          RewriteCond %{REQUEST_URI} !^/$BRANCH_NAME/
          RewriteRule ^(assets/.+|static/.+|.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf))$ /$BRANCH_NAME/$1 [L,R=301]

          # Handle client-side routing
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /$BRANCH_NAME/index.html [L]
          EOL

      - name: Deploy dist folder to server via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WEKODE_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.WEKODE_SSH_HOST }}
          REMOTE_PORT: ${{ secrets.WEKODE_SSH_PORT }}
          REMOTE_USER: ${{ secrets.WEKODE_SSH_USERNAME }}
          SOURCE: dist/
          TARGET: ${{ secrets.WEKODE_ALL_SSH_PROJECT_DIRECTORY }}/${{ steps.get_branch.outputs.branch }}
          CLEAN: true
