name: Deploy React App to Subfolder by Branch

on:
  push:
    branches:
      - '**' # triggers on all branches

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.11.0'

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Get branch name
      id: get_branch
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        BRANCH_NAME=${BRANCH_NAME//\//-} # replace / with -
        echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

    - name: Fix asset paths in index.html
      run: |
        sed -i "s|/static|/${{ steps.get_branch.outputs.branch }}/static|g" dist/index.html

    - name: Add .htaccess for SPA routing
      run: |
        echo '<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /${{ steps.get_branch.outputs.branch }}/
        RewriteRule ^index\.html$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /${{ steps.get_branch.outputs.branch }}/index.html [L]
        </IfModule>' > dist/.htaccess

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.WEKODE_SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.WEKODE_SSH_HOST }}
        REMOTE_PORT: ${{ secrets.WEKODE_SSH_PORT }}
        REMOTE_USER: ${{ secrets.WEKODE_SSH_USERNAME }}
        SOURCE: dist/
        TARGET: ${{ secrets.WEKODE_MAIN_SSH_PROJECT_DIRECTORY }}/${{ steps.get_branch.outputs.branch }}
        CLEAN: true
