name: Publish app to Dev
on:
  push:
    branches:
      - main
jobs:
  SSH-Deploy-Action:
    name: SSH-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.11.0'

    - name: Install Frontend Dependencies
      run: npm ci

    - name: Build Frontend
      run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.WEKODE_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.WEKODE_SSH_HOST }}
          REMOTE_PORT: ${{ secrets.WEKODE_SSH_PORT }}
          REMOTE_USER: ${{ secrets.WEKODE_SSH_USERNAME }}
          TARGET: ${{ secrets.WEKODE_MAIN_SSH_PROJECT_DIRECTORY }}
